export const data = [
  {
    key: '§',
    row: 1,
    size: 'key',
    keyEng: '±',
    keyRu: '>',
    upperEng: '§',
    upperRu: '<',
    type: 'key',
  },
  {
    key: '1',
    row: 1,
    size: 'key',
    keyEng: '1',
    keyRu: '1',
    upperEng: '!',
    upperRu: '!',
    type: 'key',
  },
  {
    key: '2',
    row: 1,
    size: 'key',
    keyEng: '2',
    keyRu: '2',
    upperEng: '@',
    upperRu: '"',
    type: 'key',
  },
  {
    key: '3',
    row: 1,
    size: 'key',
    keyEng: '3',
    keyRu: '3',
    upperEng: '#',
    upperRu: '№',
    type: 'key',
  },
  {
    key: '4',
    row: 1,
    size: 'key',
    keyEng: '4',
    keyRu: '4',
    upperEng: '$',
    upperRu: '%',
    type: 'key',
  },
  {
    key: '5',
    row: 1,
    size: 'key',
    keyEng: '5',
    keyRu: '5',
    upperEng: '%',
    upperRu: ':',
    type: 'key',
  },
  {
    key: '6',
    row: 1,
    size: 'key',
    keyEng: '6',
    keyRu: '6',
    upperEng: '^',
    upperRu: ',',
    type: 'key',
  },
  {
    key: '7',
    row: 1,
    size: 'key',
    keyEng: '7',
    keyRu: '7',
    upperEng: '&',
    upperRu: '.',
    type: 'key',
  },
  {
    key: '8',
    row: 1,
    size: 'key',
    keyEng: '8',
    keyRu: '8',
    upperEng: '*',
    upperRu: ';',
    type: 'key',
  },
  {
    key: '9',
    row: 1,
    size: 'key',
    keyEng: '9',
    keyRu: '9',
    upperEng: '(',
    upperRu: '(',
    type: 'key',
  },
  {
    key: '0',
    row: 1,
    size: 'key',
    keyEng: '0',
    keyRu: '0',
    upperEng: ')',
    upperRu: ')',
    type: 'key',
  },
  {
    key: '-',
    row: 1,
    size: 'key',
    keyEng: '-',
    keyRu: '-',
    upperEng: '_',
    upperRu: '_',
    type: 'key',
  },
  {
    key: '=',
    row: 1,
    size: 'key',
    keyEng: '=',
    keyRu: '+',
    upperEng: '=',
    upperRu: '+',
    type: 'key',
  },
  {
    key: 'Backspace',
    row: 1,
    size: 'backspace',
    keyEng: 'backspace',
    keyRu: 'backspace',
    upperEng: 'backspace',
    upperRu: 'backspace',
    type: 'specialKey',
  },
  {
    key: 'Tab',
    row: 2,
    size: 'tab',
    keyEng: 'tab',
    keyRu: 'tab',
    upperEng: 'tab',
    upperRu: 'tab',
    type: 'specialKey',
  },
  {
    key: 'q',
    row: 2,
    size: 'key',
    keyEng: 'q',
    keyRu: 'й',
    upperEng: 'Q',
    upperRu: 'Й',
    type: 'key',
  },
  {
    key: 'w',
    row: 2,
    size: 'key',
    keyEng: 'w',
    keyRu: 'ц',
    upperEng: 'W',
    upperRu: 'Ц',
    type: 'key',
  },
  {
    key: 'e',
    row: 2,
    size: 'key',
    keyEng: 'e',
    keyRu: 'у',
    upperEng: 'E',
    upperRu: 'У',
    type: 'key',
  },
  {
    key: 'r',
    row: 2,
    size: 'key',
    keyEng: 'r',
    keyRu: 'к',
    upperEng: 'R',
    upperRu: 'К',
    type: 'key',
  },
  {
    key: 't',
    row: 2,
    size: 'key',
    keyEng: 't',
    keyRu: 'е',
    upperEng: 'T',
    upperRu: 'Е',
    type: 'key',
  },
  {
    key: 'y',
    row: 2,
    size: 'key',
    keyEng: 'y',
    keyRu: 'н',
    upperEng: 'Y',
    upperRu: 'Н',
    type: 'key',
  },
  {
    key: 'u',
    row: 2,
    size: 'key',
    keyEng: 'u',
    keyRu: 'г',
    upperEng: 'U',
    upperRu: 'Г',
    type: 'key',
  },
  {
    key: 'i',
    row: 2,
    size: 'key',
    keyEng: 'i',
    keyRu: 'ш',
    upperEng: 'I',
    upperRu: 'Ш',
    type: 'key',
  },
  {
    key: 'o',
    row: 2,
    size: 'key',
    keyEng: 'o',
    keyRu: 'щ',
    upperEng: 'O',
    upperRu: 'Щ',
    type: 'key',
  },
  {
    key: 'p',
    row: 2,
    size: 'key',
    keyEng: 'p',
    keyRu: 'з',
    upperEng: 'P',
    upperRu: 'З',
    type: 'key',
  },
  {
    key: '[',
    row: 2,
    size: 'key',
    keyEng: '[',
    keyRu: 'х',
    upperEng: '{',
    upperRu: 'Х',
    type: 'key',
  },
  {
    key: ']',
    row: 2,
    size: 'key',
    keyEng: ']',
    keyRu: 'ъ',
    upperEng: '}',
    upperRu: 'Ъ',
    type: 'key',
  },
  {
    key: '\/',
    row: 2,
    size: 'key',
    keyEng: '\/',
    keyRu: '\/',
    upperEng: '|',
    upperRu: '|',
    type: 'key',
  },
  {
    key: 'CapsLock',
    row: 3,
    size: 'capslock',
    keyEng: 'caps lock',
    keyRu: 'caps lock',
    upperEng: 'caps lock',
    upperRu: 'caps lock',
    type: 'specialKey',
  },
  {
    key: 'a',
    row: 3,
    size: 'key',
    keyEng: 'a',
    keyRu: 'ф',
    upperEng: 'A',
    upperRu: 'Ф',
    type: 'key',
  },
  {
    key: 's',
    row: 3,
    size: 'key',
    keyEng: 's',
    keyRu: 'ы',
    upperEng: 'S',
    upperRu: 'Ы',
    type: 'key',
  },
  {
    key: 'd',
    row: 3,
    size: 'key',
    keyEng: 'd',
    keyRu: 'в',
    upperEng: 'D',
    upperRu: 'В',
    type: 'key',
  },
  {
    key: 'f',
    row: 3,
    size: 'key',
    keyEng: 'f',
    keyRu: 'а',
    upperEng: 'F',
    upperRu: 'А',
    type: 'key',
  },
  {
    key: 'g',
    row: 3,
    size: 'key',
    keyEng: 'g',
    keyRu: 'п',
    upperEng: 'G',
    upperRu: 'П',
    type: 'key',
  },
  {
    key: 'h',
    row: 3,
    size: 'key',
    keyEng: 'h',
    keyRu: 'р',
    upperEng: 'H',
    upperRu: 'Р',
    type: 'key',
  },
  {
    key: 'j',
    row: 3,
    size: 'key',
    keyEng: 'j',
    keyRu: 'о',
    upperEng: 'J',
    upperRu: 'О',
    type: 'key',
  },
  {
    key: 'k',
    row: 3,
    size: 'key',
    keyEng: 'k',
    keyRu: 'л',
    upperEng: 'K',
    upperRu: 'Л',
    type: 'key',
  },
  {
    key: 'l',
    row: 3,
    size: 'key',
    keyEng: 'l',
    keyRu: 'д',
    upperEng: 'L',
    upperRu: 'Д',
    type: 'key',
  },
  {
    key: ';',
    row: 3,
    size: 'key',
    keyEng: ';',
    keyRu: 'ж',
    upperEng: ':',
    upperRu: 'Ж',
    type: 'key',
  },
  {
    key: '\'',
    row: 3,
    size: 'key',
    keyEng: '\'',
    keyRu: 'э',
    upperEng: '"',
    upperRu: 'Э',
    type: 'key',
  },
  {
    key: 'Enter',
    row: 3,
    size: 'return',
    keyEng: 'return',
    keyRu: 'return',
    upperEng: 'return',
    upperRu: 'return',
    type: 'specialKey',
  },
  {
    key: 'Shift',
    row: 4,
    size: 'shift',
    keyEng: 'shift',
    keyRu: 'shift',
    upperEng: 'shift',
    upperRu: 'shift',
    type: 'specialKey',
  },
  {
    key: '`',
    row: 4,
    size: 'key',
    keyEng: '`',
    keyRu: ']',
    upperEng: '~',
    upperRu: '[',
    type: 'key',
  },
  {
    key: 'z',
    row: 4,
    size: 'key',
    keyEng: 'z',
    keyRu: 'я',
    upperEng: 'Z',
    upperRu: 'Я',
    type: 'key',
  },
  {
    key: 'x',
    row: 4,
    size: 'key',
    keyEng: 'x',
    keyRu: 'ч',
    upperEng: 'X',
    upperRu: 'Ч',
    type: 'key',
  },
  {
    key: 'c',
    row: 4,
    size: 'key',
    keyEng: 'c',
    keyRu: 'с',
    upperEng: 'C',
    upperRu: 'С',
    type: 'key',
  },
  {
    key: 'v',
    row: 4,
    size: 'key',
    keyEng: 'v',
    keyRu: 'м',
    upperEng: 'V',
    upperRu: 'М',
    type: 'key',
  },
  {
    key: 'b',
    row: 4,
    size: 'key',
    keyEng: 'b',
    keyRu: 'и',
    upperEng: 'B',
    upperRu: 'И',
    type: 'key',
  },
  {
    key: 'n',
    row: 4,
    size: 'key',
    keyEng: 'n',
    keyRu: 'т',
    upperEng: 'N',
    upperRu: 'Т',
    type: 'key',
  },
  {
    key: 'm',
    row: 4,
    size: 'key',
    keyEng: 'm',
    keyRu: 'ь',
    upperEng: 'M',
    upperRu: 'Ь',
    type: 'key',
  },
  {
    key: ',',
    row: 4,
    size: 'key',
    keyEng: ',',
    keyRu: 'б',
    upperEng: '<',
    upperRu: 'Б',
    type: 'key',
  },
  {
    key: '.',
    row: 4,
    size: 'key',
    keyEng: '.',
    keyRu: 'ю',
    upperEng: '>',
    upperRu: 'Ю',
    type: 'key',
  },
  {
    key: '/',
    row: 4,
    size: 'key',
    keyEng: '/',
    keyRu: '/',
    upperEng: '?',
    upperRu: '?',
    type: 'key',
  },
  {
    key: 'Shift',
    row: 4,
    size: 'shift',
    keyEng: 'shift',
    keyRu: 'shift',
    upperEng: 'shift',
    upperRu: 'shift',
    type: 'specialKey',
  },
  {
    key: 'Fn',
    row: 5,
    size: 'fn',
    keyEng: 'fn',
    keyRu: 'fn',
    upperEng: 'fn',
    upperRu: 'fn',
    type: 'specialKey',
  },
  {
    key: 'Control',
    row: 5,
    size: 'control',
    keyEng: 'control',
    keyRu: 'control',
    upperEng: 'control',
    upperRu: 'control',
    type: 'specialKey',
  },
  {
    key: 'Alt',
    row: 5,
    size: 'option',
    keyEng: 'option',
    keyRu: 'option',
    upperEng: 'option',
    upperRu: 'option',
    type: 'specialKey',
  },
  {
    key: 'Meta',
    row: 5,
    size: 'command',
    keyEng: 'command',
    keyRu: 'command',
    upperEng: 'command',
    upperRu: 'command',
    type: 'specialKey',
  },
  {
    key: ' ',
    row: 5,
    size: 'space',
    keyEng: ' ',
    keyRu: ' ',
    upperEng: ' ',
    upperRu: ' ',
    type: 'specialKey',
  },
  {
    key: 'Meta',
    row: 5,
    size: 'command',
    keyEng: 'command',
    keyRu: 'command',
    upperEng: 'command',
    upperRu: 'command',
    type: 'specialKey',
  },
  {
    key: 'Alt',
    row: 5,
    size: 'option',
    keyEng: 'option',
    keyRu: 'option',
    upperEng: 'option',
    upperRu: 'option',
    type: 'specialKey',
  },
  {
    key: 'ArrowLeft',
    row: 5,
    size: 'arrowLeft',
    keyEng: '',
    keyRu: '',
    upperEng: '',
    upperRu: '',
    type: 'arrow',
  },
  {
    key: 'ArrowUp',
    row: 5,
    size: 'arrowUp',
    keyEng: '',
    keyRu: '',
    upperEng: '',
    upperRu: '',
    type: 'arrow',
  },
  {
    key: 'ArrowDown',
    row: 5,
    size: 'arrowDown',
    keyEng: '',
    keyRu: '',
    upperEng: '',
    upperRu: '',
    type: 'arrow',
  },
  {
    key: 'ArrowRight',
    row: 5,
    size: 'arrowRight',
    keyEng: '',
    keyRu: '',
    upperEng: '',
    upperRu: '',
    type: 'arrow',
  },
];
